// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type InputNewPaymentGql struct {
	ID          int    `json:"id"`
	Value       int    `json:"value"`
	Chanel      string `json:"chanel"`
	Code        string `json:"code"`
	Description string `json:"description"`
	Image       string `json:"image"`
	Limit       int    `json:"limit"`
	Status      bool   `json:"status"`
	Tipe        int    `json:"tipe"`
	Title       string `json:"title"`
	TitleType   string `json:"titleType"`
}

type InputRemoteConfigGql struct {
	Baseurl               *string `json:"baseurl"`
	BaseURLPrakerja       *string `json:"baseUrlPrakerja"`
	ForceLogout           *int    `json:"forceLogout"`
	IsChecking            *int    `json:"isChecking"`
	IsMaintenance         *int    `json:"isMaintenance"`
	IsMaintenancePrakerja *int    `json:"isMaintenancePrakerja"`
	NewVersion            *int    `json:"newVersion"`
}

type PaymentMethodGql struct {
	ID          int    `json:"ID"`
	Value       int    `json:"Value"`
	Chanel      string `json:"Chanel"`
	Code        string `json:"Code"`
	Description string `json:"Description"`
	Image       string `json:"Image"`
	Limit       int    `json:"Limit"`
	Status      bool   `json:"Status"`
	Tipe        int    `json:"Tipe"`
	Title       string `json:"Title"`
	TitleType   string `json:"TitleType"`
}

type RemoteConfigGql struct {
	BaseURL              *string `json:"BaseUrl"`
	BaseURLPrakerja      *string `json:"BaseUrlPrakerja"`
	ForceLogout          *int    `json:"ForceLogout"`
	IsChecking           *int    `json:"IsChecking"`
	IsMantenance         *int    `json:"IsMantenance"`
	IsMantenancePrakerja *int    `json:"IsMantenancePrakerja"`
	NewVersion           *int    `json:"NewVersion"`
}
